[package]
name = "pipette-mgmt-client"
version = "0.1.0"
edition = "2021"
publish = false

[lints]
workspace = true

[dependencies]
ed25519-dalek.workspace = true
getrandom.workspace = true
hex.workspace = true
nutype.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
time.workspace = true
url.workspace = true
reqwest = { workspace = true, features = ["blocking"] }
pipette-http.workspace = true

[dev-dependencies]
httpmock.workspace = true
rstest.workspace = true
toml.workspace = true
